In [1]:
import pandas as pd
import numpy as np
import sqlite3 as sql
data=pd.read_csv('raw data/IPC district wise crime rate.csv',index_col=0)
data.head(10)

,year,state_name,state_code,district_name,district_code,registration_circles,murder,attempt_to_commit_murder,culpable_homicide_not_amounting_to_murder,attempt_to_commit_culpable_homicide,...,importation_of_girls_from_foreign_country,causing_death_by_negligence,offences_against_state,offences_promoting_enmity_between_diff_grp,extortion,disclosure_of_identity_of_victims,incidence_of_rash_driving,human_trafficking,unnatural_offence,other_ipc_crimes
id,,,,,,,,,,,,,,,,,,,,,
0,2016,Andhra Pradesh,28,Anantapur,502,Anantapur,127,195,6,0,...,0,588,0,0,29,0,862,0,0,3200
1,2016,Andhra Pradesh,28,Chittoor,503,Chittoor,72,73,3,0,...,0,590,0,0,20,0,738,0,0,1429
2,2016,Andhra Pradesh,28,Y.S.R.,504,Cuddapah,78,257,6,0,...,0,480,0,0,38,0,2520,8,0,1987
3,2016,Andhra Pradesh,28,East Godavari,505,East Godavari,64,78,9,0,...,0,625,0,0,55,0,1244,0,0,2643
4,2016,Andhra Pradesh,28,Anantapur,502,Guntakal Railway,8,0,0,0,...,0,1,0,0,0,0,3,0,0,30
5,2016,Andhra Pradesh,28,Guntur,506,Guntur,109,157,4,0,...,0,604,0,0,23,0,860,0,1,2251
6,2016,Andhra Pradesh,28,Guntur,506,Guntur Urban,40,50,3,0,...,0,291,0,5,46,0,636,1,0,1126
7,2016,Andhra Pradesh,28,Krishna,510,Krishna,48,63,5,0,...,0,454,0,0,16,0,1000,1,1,2775
8,2016,Andhra Pradesh,28,Kurnool,511,Kurnool,119,298,7,0,...,0,620,0,1,45,0,1331,0,0,3268
9,2016,Andhra Pradesh,28,Spsr Nellore,515,Nellore,74,148,6,0,...,0,462,0,0,24,0,1028,0,0,2763

In [3]:
data_delhi=data.loc[data.state_name=='Delhi']
data_delhi=data_delhi.drop(columns=['state_code','district_code', 'registration_circles','state_name','year',])
data_delhi

,district_name,murder,attempt_to_commit_murder,culpable_homicide_not_amounting_to_murder,attempt_to_commit_culpable_homicide,rape,attempt_to_commit_rape,kidnapping_and_abduction,dacoity,mkng_preparation_and_assembly_for_comm_dacoity,...,importation_of_girls_from_foreign_country,causing_death_by_negligence,offences_against_state,offences_promoting_enmity_between_diff_grp,extortion,disclosure_of_identity_of_victims,incidence_of_rash_driving,human_trafficking,unnatural_offence,other_ipc_crimes
id,,,,,,,,,,,,,,,,,,,,,
795,Central,31,28,4,61,104,1,240,1,0,...,0,78,0,0,8,0,1517,5,14,1647
796,North West,2,6,0,0,1,0,2,0,0,...,0,0,0,0,5,0,0,0,0,0
797,East,34,59,4,75,221,3,651,3,0,...,0,111,0,0,31,0,845,4,14,2308
798,New Delhi,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
799,New Delhi,0,0,0,0,0,0,1,0,0,...,0,4,0,0,0,0,19,0,0,48
800,North West,1,1,0,0,1,0,6,0,0,...,0,1,0,0,0,0,0,0,0,15
801,New Delhi,7,6,0,5,23,1,50,0,0,...,0,69,1,0,5,0,286,0,2,244
802,North,26,25,6,31,65,0,272,3,0,...,0,154,0,0,9,1,810,0,9,1131
803,North East,51,117,4,229,223,5,826,2,1,...,0,132,0,0,14,0,641,3,27,2918
804,North West,46,75,3,53,190,6,609,10,1,...,0,190,0,0,21,0,1920,5,20,1568
805,North West,101,83,9,81,372,1,1037,5,2,...,0,302,0,0,32,1,831,5,29,2783
806,New Delhi,6,5,0,0,7,0,40,1,0,...,0,1,0,0,1,0,6,2,0,321
807,South,43,37,8,85,246,9,601,6,1,...,0,161,1,0,25,0,873,3,13,1556
808,South East,58,72,4,72,275,1,765,4,0,...,0,193,0,0,17,0,912,1,20,1298
809,South West,58,48,3,66,171,1,762,6,0,...,0,212,0,0,29,0,873,1,15,1130
810,North West,0,5,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
811,New Delhi,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
812,New Delhi,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
813,West,64,79,9,87,256,1,757,5,0,...,0,248,0,0,29,0,1106,2,19,2346

In [4]:
data_delhi['district_name'].value_counts()

district_name
New Delhi     6
North West    5
Central       1
East          1
North         1
North East    1
South         1
South East    1
South West    1
West          1
Name: count, dtype: int64

In [5]:
district_delhi=data_delhi.groupby('district_name').sum()
district_delhi['total_crimes']=district_delhi.sum(axis=1)
print(district_delhi.columns)
district_delhi
property_crime = ["robbery","dacoity","mkng_preparation_and_assembly_for_comm_dacoity","extortion",'criminal_trespass_or_burglary',"theft"]
violent = ["murder","attempt_to_commit_murder","culpable_homicide_not_amounting_to_murder","attempt_to_commit_culpable_homicide","rape","attempt_to_commit_rape","kidnapping_and_abduction","human_trafficking"]
women_crime = ["rape","attempt_to_commit_rape","assault_on_women","cruelty_by_husband_or_his_relatives"]
social = ["offences_promoting_enmity_between_diff_grp","unnatural_offence"]
public_safety = ["causing_death_by_negligence","incidence_of_rash_driving"]
district_delhi['property_crime']=district_delhi[property_crime].sum(axis=1)
district_delhi['violent_crime']=district_delhi[violent].sum(axis=1)
district_delhi['women_crime']=district_delhi[women_crime].sum(axis=1) 
district_delhi['social_crime']=district_delhi[social].sum(axis=1)
district_delhi['public_safety']=district_delhi[public_safety].sum(axis=1)

Index(['murder', 'attempt_to_commit_murder',
       'culpable_homicide_not_amounting_to_murder',
       'attempt_to_commit_culpable_homicide', 'rape', 'attempt_to_commit_rape',
       'kidnapping_and_abduction', 'dacoity',
       'mkng_preparation_and_assembly_for_comm_dacoity', 'robbery',
       'criminal_trespass_or_burglary', 'theft', 'unlawful_assembly', 'riots',
       'criminal_breach_of_trust', 'cheating', 'forgery', 'counterfeiting',
       'arson', 'grievous_hurt', 'dowry_deaths', 'assault_on_women',
       'insult_to_the_modesty_of_women', 'cruelty_by_husband_or_his_relatives',
       'importation_of_girls_from_foreign_country',
       'causing_death_by_negligence', 'offences_against_state',
       'offences_promoting_enmity_between_diff_grp', 'extortion',
       'disclosure_of_identity_of_victims', 'incidence_of_rash_driving',
       'human_trafficking', 'unnatural_offence', 'other_ipc_crimes',
       'total_crimes'],
      dtype='str')

In [6]:
df = district_delhi[
    [
        'property_crime',
        'violent_crime',
        'women_crime',
        'social_crime',
        'public_safety',
        'total_crimes'
    ]
].reset_index()
numeric_cols=df.columns.drop("district_name")
df.loc[6, numeric_cols]+=df.loc[7 , numeric_cols]
df.loc[6,"district_name"]= "South"
df=df.drop(index=7).reset_index(drop=True)
df

,district_name,property_crime,violent_crime,women_crime,social_crime,public_safety,total_crimes
0,Central,7762,474,441,14,1595,12149
1,East,16011,1051,1049,14,956,21789
2,New Delhi,6108,153,348,2,385,8316
3,North,8212,425,361,9,964,11438
4,North East,13711,1458,1215,27,773,20338
5,North West,41857,2701,2426,49,3244,55707
6,South,28694,2280,2241,33,2139,40089
7,South West,8395,1110,887,15,1085,13207
8,West,19523,1255,1258,19,1354,26486

In [7]:

df.to_csv("crime_module_1.csv",index=False)