In [1]:
import pandas as pd
import numpy as np
import sqlite3 as sql 
data=pd.read_csv("processed_data/demography_module_2.csv",)
data

,district_name,population,area,population_density,sex_ratio,literacy,total_workers,non_workers,WPR
0,Central,582320,21,27729.523810,892,85.14,207374,374946,35.611691
1,East,1709346,63,27132.476190,884,89.31,579692,1129654,33.913087
2,New Delhi,142004,35,4057.257143,822,88.34,59541,82463,41.929101
3,North,887978,61,14557.016393,869,86.85,296446,591532,33.384386
4,North East,2241624,62,36155.225806,886,83.12,655398,1564699,29.237642
5,North West,3656539,443,8254.038375,865,84.74,1121005,2321536,30.657543
6,South,2731929,247,11060.441296,862,86.57,924393,1807536,33.836641
7,South West,2292958,421,5446.456057,840,88.28,795352,1497606,34.686723
8,West,2543243,130,19563.407692,875,86.98,874320,1668923,34.378154

In [2]:
import pandas as pd

economy = pd.DataFrame({
    "district_name": [
        "Central",
        "East",
        "New Delhi",
        "North",
        "North East",
        "North West",
        "South",
        "South West",
        "West"
    ], "Area": data["area"],
    "population": data["population"],
    "establishments": [
        150671,
        80061 + 71738,      
        38153,
        73724,
        86597,
        93297,
        57126 + 75049,      
        42166,
        106726
    ],
    "persons_employed": [
        599058,
        215979 + 229663,
        269225,
        318960,
        183313,
        286189,
        145304 + 352562,
        105954,
        313574
    ]
})

economy["employment_per_establishment"] = (economy["persons_employed"] /economy["establishments"]).round(2)
economy["establishment_density"]=(economy["establishments"]/economy["Area"]).round(2)
economy["employment_rate"]=(economy["persons_employed"]/economy["population"])
economy

,district_name,Area,population,establishments,persons_employed,employment_per_establishment,establishment_density,employment_rate
0,Central,21,582320,150671,599058,3.98,7174.81,1.028744
1,East,63,1709346,151799,445642,2.94,2409.51,0.260709
2,New Delhi,35,142004,38153,269225,7.06,1090.09,1.895897
3,North,61,887978,73724,318960,4.33,1208.59,0.359198
4,North East,62,2241624,86597,183313,2.12,1396.73,0.081777
5,North West,443,3656539,93297,286189,3.07,210.60,0.078268
6,South,247,2731929,132175,497866,3.77,535.12,0.182240
7,South West,421,2292958,42166,105954,2.51,100.16,0.046208
8,West,130,2543243,106726,313574,2.94,820.97,0.123297

In [3]:
economy.to_csv("Economy_module_3.csv",index=False)